import {
  CheckCircle2,
  Clock,
  FileText,
  UserPlus,
  FileSignature,
} from "lucide-react";
import { useState, useEffect } from "react";
import { apiFetch } from "../lib/api";

export function ActivityLogs() {
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState("All");

  const filters = [
    { label: "All", query: "" },
    { label: "RFQ", query: "RFQ" },
    { label: "Approvals", query: "Quotation,PurchaseOrder" },
    { label: "Invoices", query: "Invoice" },
    { label: "Vendors", query: "Vendor" },
  ];

  useEffect(() => {
    async function fetchLogs() {
      setLoading(true);
      try {
        const filterObj = filters.find((f) => f.label === activeFilter);
        const endpoint = filterObj?.query
          ? `/logs?entityType=${filterObj.query}`
          : "/logs";
        const data = await apiFetch(endpoint);
        setLogs(data);
      } catch (err) {
        console.error("Failed to load activity logs", err);
      } finally {
        setLoading(false);
      }
    }
    fetchLogs();
  }, [activeFilter]);

  const getLogDetails = (log: any) => {
    switch (log.action) {
      case "CREATED_RFQ":
        return {
          icon: FileText,
          color: "text-blue-500",
          desc: `RFQ Created by ${log.performedBy.name}`,
        };
      case "SUBMITTED_QUOTATION":
        return {
          icon: FileSignature,
          color: "text-amber-500",
          desc: `Quotation submitted by vendor ${log.performedBy.name}`,
        };
      case "APPROVED_QUOTATION":
        return {
          icon: CheckCircle2,
          color: "text-emerald-500",
          desc: `Quotation approved by ${log.performedBy.name}`,
        };
      case "GENERATED_PO":
        return {
          icon: Clock,
          color: "text-purple-500",
          desc: `Purchase Order generated by ${log.performedBy.name}`,
        };
      case "REGISTERED_VENDOR":
        return {
          icon: UserPlus,
          color: "text-indigo-400",
          desc: `Vendor registered by ${log.performedBy.name}`,
        };
      case "GENERATED_INVOICE":
        return {
          icon: FileText,
          color: "text-teal-400",
          desc: `Invoice generated by ${log.performedBy.name}`,
        };
      case "EMAILED_INVOICE":
        return {
          icon: FileText,
          color: "text-pink-400",
          desc: `Invoice emailed by ${log.performedBy.name}`,
        };
      default:
        return {
          icon: Clock,
          color: "text-gray-400",
          desc: `${log.action} performed by ${log.performedBy.name}`,
        };
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-4xl">
      <div>
        <h1 className="text-3xl font-semibold text-gray-100">
          Activity & Logs
        </h1>
        <p className="text-sm text-gray-400 mt-1">Procurement audit trail</p>
      </div>

      <div className="flex flex-wrap gap-2 pb-4">
        {filters.map((filter, i) => (
          <button
            key={i}
            onClick={() => setActiveFilter(filter.label)}
            className={`px-6 py-1.5 rounded-full text-sm font-medium border transition-colors ${activeFilter === filter.label ? "bg-blue-600 border-blue-500 text-white" : "bg-transparent border-zinc-700 text-gray-400 hover:text-white hover:bg-zinc-800"}`}
          >
            {filter.label}
          </button>
        ))}
      </div>

      <div className="space-y-6">
        {loading ? (
          <div className="text-gray-400">Loading activity...</div>
        ) : logs.length === 0 ? (
          <div className="text-gray-500 text-sm">
            No activity recorded for this category yet.
          </div>
        ) : (
          logs.map((log) => {
            const { icon: Icon, color, desc } = getLogDetails(log);
            return (
              <div
                key={log.id}
                className="flex gap-4 items-start border-b border-zinc-800 pb-6 last:border-0 hover:bg-zinc-900/30 p-2 -mx-2 rounded transition-colors text-sm"
              >
                <div className="bg-zinc-800/50 p-2 rounded-full mt-1 border border-zinc-700/50">
                  <Icon className={`w-5 h-5 ${color}`} />
                </div>
                <div className="space-y-1">
                  <p className="text-gray-200 leading-relaxed font-medium">
                    {desc}{" "}
                    <span className="text-gray-500 font-normal">
                      ({log.entityType} ID: {log.entityId.substring(0, 8)}...)
                    </span>
                  </p>
                  <p className="text-xs text-zinc-500">
                    {new Date(log.createdAt).toLocaleString()}
                  </p>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
